# Structured source of truth for /marques/ editorial content.
# Product-state and feature claims were researched from official manufacturer
# documentation on 2026-09-08. No first-hand testing is claimed.

VERIFIED_AT = "8 septembre 2026"

BRAND_SOURCES = {
    "remarkable": [
        ("Gamme reMarkable actuelle", "https://remarkable.com/fr-fr"),
        ("Comparateur officiel reMarkable", "https://remarkable.com/fr-FR/shop/compare"),
        ("reMarkable Paper Pro", "https://remarkable.com/fr-FR/products/remarkable-paper/pro?region_id=000250"),
        ("reMarkable Paper Pure", "https://remarkable.com/fr-FR/products/remarkable-paper/pure/details/features"),
        ("reMarkable 2", "https://remarkable.com/products/remarkable-2"),
        ("Marker pour reMarkable 2", "https://remarkable.com/fr-FR/products/remarkable-2/markers"),
        ("Mines Marker nouvelle génération", "https://remarkable.com/fr-FR/products/remarkable-paper/marker-tips"),
    ],
    "boox": [
        ("Gamme BOOX", "https://shop.boox.com/collections/all-products/reading-tools"),
        ("Série Note BOOX", "https://shop.boox.com/collections/noteseries"),
        ("BOOX Go 10.3 Gen II", "https://shop.boox.com/products/go103gen2"),
        ("BOOX Note Air5 C", "https://shop.boox.com/products/noteair5c"),
        ("BOOX Note Max", "https://shop.boox.com/products/notemax"),
        ("BOOX Tab X C", "https://shop.boox.com/products/tabxc"),
        ("BOOX Tab Ultra C Pro", "https://shop.boox.com/products/tabultracpro"),
        ("Stockage cloud tiers BOOX", "https://help.boox.com/hc/en-us/articles/8569457124628-Integrated-Third-Party-Cloud-Storage"),
        ("Notes manuscrites BOOX", "https://help.boox.com/hc/en-us/articles/8569373888788-Handwritten-Notes"),
        ("Synchronisation de lecture BOOX", "https://help.boox.com/hc/en-us/articles/25096430940436-Reading-Data-Syncing-and-Backup"),
    ],
    "kindle": [
        ("Identifier les générations Kindle", "https://digprjsurvey.amazon.com/csad/help/node/GK33S847NN4V6Y83"),
        ("Guides Kindle Scribe", "https://digprjsurvey.amazon.com/csad/help/node/G7N7RPHV2SW8CKBW"),
        ("Connexion Google Drive / OneDrive / OneNote", "https://digprjsurvey.amazon.com/csad/help/node/Tuar1obhcxaS8hVUKd"),
        ("Importer depuis Drive / OneDrive", "https://digprjsurvey.amazon.com/csad/help/node/TjrMJmg3DZpAQLwVuN"),
        ("Partager vers Drive / OneDrive / OneNote", "https://digprjsurvey.amazon.com/csad/help/node/TP8wuaQilIlwlITVTL"),
        ("FAQ cloud Kindle Scribe", "https://digprjsurvey.amazon.com/csad/help/node/TIh9JOMGAKr7bY4zqu"),
        ("Partager notes et carnets", "https://digprjsurvey.amazon.com/csad/help/node/TJE2UYmdw0ppUuR3Rs"),
    ],
    "kobo": [
        ("Kobo Elipsa 2E", "https://ereader.kobo.com/fr-fr/products/kobo-elipsa-2e"),
        ("Utiliser Kobo comme carnet", "https://help.kobo.com/hc/fr/articles/360062226733-Utiliser-votre-liseuse-Kobo-comme-un-carnet"),
        ("Google Drive sur Kobo", "https://help.kobo.com/hc/fr/articles/15335985512983-Ajouter-des-livres-sur-votre-liseuse-%C3%A0-l-aide-de-Google-Drive"),
        ("Annotations au stylet Kobo", "https://help.kobo.com/hc/fr/articles/1500001927562-Annoter-votre-livre-avec-le-stylet-Kobo"),
        ("Documentation Elipsa 2E", "https://www.kobo.com/fr/fr/p/support-documents"),
    ],
    "supernote": [
        ("Supernote Manta", "https://supernote.com/products/supernote-manta"),
        ("Supernote Nomad", "https://supernote.com/products/supernote-nomad"),
        ("Évolution des noms Supernote", "https://supernote.com/blogs/supernote-blog/an-explanation-of-supernote-product-naming-evolution"),
        ("Reconnaissance manuscrite Supernote", "https://support.supernote.com/en_US/Tools-Features/handwriting-recognition"),
        ("Transfert de fichiers Supernote", "https://support.supernote.com/en_US/transfer-files"),
    ],
}

BRANDS = {
    "remarkable": {
        "name": "reMarkable",
        "positioning": "un écosystème volontairement spécialisé dans l’écriture, la lecture de documents et le travail sans distractions, avec une gamme actuelle structurée entre noir et blanc, mobilité et grand écran couleur",
        "current_range": [
            ("Paper Pure", "CURRENT", "10,3″, noir et blanc", "écriture et notes concentrées", "pas d’applications tierces généralistes"),
            ("Paper Pro Move", "CURRENT", "format compact, couleur", "mobilité et notes rapides", "surface plus petite pour grands PDF"),
            ("Paper Pro", "CURRENT", "11,8″, couleur", "grands documents, couleur, écriture", "coût de configuration élevé"),
            ("reMarkable 2", "DISCONTINUED", "10,3″, noir et blanc", "ancienne génération encore documentée", "markers incompatibles avec la nouvelle génération"),
        ],
        "ecosystem": [
            ("Matériel", "Paper Pure, Paper Pro Move, Paper Pro ; reMarkable 2 reste documentée comme génération précédente."),
            ("Stylet", "Marker / Marker Plus ; la compatibilité dépend de la génération de tablette."),
            ("Système", "reMarkable OS, système Linux spécialisé pour papier numérique."),
            ("Notes", "carnets, dossiers, étiquettes, modèles, conversion manuscrite."),
            ("Documents", "import PDF/EPUB et export PDF/PNG/SVG selon les fonctions."),
            ("Cloud", "cloud reMarkable ; certaines fonctions avancées et stockage illimité passent par Connect."),
            ("Intégrations", "Google Drive, OneDrive, Dropbox et outils de travail selon le niveau de service."),
            ("Applications", "apps bureau/mobile ; ce n’est pas une tablette Android généraliste."),
        ],
        "strengths": [
            "interface spécialisée et cohérente pour écrire et relire",
            "gamme lisible : noir et blanc, compact couleur ou grand écran couleur",
            "workflow mobile/desktop et export documentaire bien intégré",
        ],
        "limits": [
            "écosystème plus fermé que BOOX",
            "certaines fonctions cloud et applicatives avancées sont liées à Connect",
            "compatibilité des Markers à vérifier entre reMarkable 2 et la génération Paper",
        ],
        "choose": [
            "vous voulez remplacer cahiers et impressions par un outil spécialisé",
            "vous privilégiez une interface simple plutôt qu’un catalogue d’applications",
            "vous travaillez surtout avec des notes manuscrites, des PDF et des documents à relire",
        ],
        "avoid": [
            "vous dépendez d’applications Android ou d’un navigateur très polyvalent",
            "vous voulez éviter tout service récurrent pour les fonctions cloud avancées",
            "vous cherchez surtout une liseuse avec une vaste boutique de livres intégrée",
        ],
    },
    "boox": {
        "name": "BOOX",
        "positioning": "des tablettes E Ink Android qui privilégient l’ouverture logicielle, la compatibilité documentaire et les applications tierces, au prix d’une interface plus riche et plus complexe",
        "current_range": [
            ("Go 10.3 (Gen II)", "CURRENT", "10,3″ noir et blanc", "notes, PDF et mobilité", "pas d’éclairage frontal sur ce positionnement minimaliste"),
            ("Note Air5 C", "CURRENT", "10,3″ Kaleido 3 couleur", "notes, couleur et productivité légère", "couleur moins vive qu’un écran LCD/OLED"),
            ("Note Max", "CURRENT", "13,3″ noir et blanc 300 ppp", "PDF A4, recherche, travail de bureau", "grand format et absence d’éclairage frontal"),
            ("Tab X C", "CURRENT", "13,3″ couleur", "grand écran couleur et productivité", "format lourd et budget élevé"),
            ("Tab Ultra C Pro", "CURRENT_DOCUMENTED", "10,3″ couleur, Android 12", "workflow type tablette avec clavier", "génération logicielle plus ancienne que Note Air5 C"),
        ],
        "ecosystem": [
            ("Matériel", "gamme large du lecteur compact au 13,3 pouces."),
            ("Stylet", "Pen Plus, Pen3 ou InkSense selon les appareils."),
            ("Système", "Android, avec versions différentes selon génération ; Google Play sur les modèles concernés."),
            ("Notes", "Notes BOOX, liens, tags, reconnaissance de texte, export PDF/PNG/.note."),
            ("Lecture", "NeoReader pour PDF, EPUB et de nombreux formats."),
            ("Cloud", "Onyx Cloud et intégrations Dropbox, Google Drive, OneDrive, WebDAV/Nextcloud selon firmware."),
            ("Synchronisation", "progression, annotations et sauvegardes selon les méthodes BOOX."),
            ("Applications", "apps tierces : avantage majeur, mais qualité variable sur E Ink."),
        ],
        "strengths": ["ouverture Android et choix d’applications", "large compatibilité de formats et outils PDF", "gamme très étendue en taille, couleur et usage"],
        "limits": ["plus de réglages, de menus et de comportements à comprendre", "toutes les applications Android ne sont pas optimisées pour E Ink", "la gamme évolue vite et exige de vérifier génération, Android et stylet"],
        "choose": ["vous avez des applications métier ou cloud à conserver", "vous manipulez beaucoup de PDF et de formats différents", "vous voulez un appareil plus proche d’une tablette polyvalente que d’un carnet fermé"],
        "avoid": ["vous recherchez une expérience ultra-minimaliste", "vous ne voulez pas gérer les réglages de rafraîchissement et d’applications", "vous préférez un écosystème dont toutes les fonctions sont pensées par un seul fabricant"],
    },
    "kindle": {
        "name": "Kindle Scribe",
        "positioning": "la branche écriture du Kindle : priorité à la lecture Amazon, complétée par carnets, annotation de documents et, sur les générations 2025+, connexions Google Drive, OneDrive et OneNote",
        "current_range": [
            ("Kindle Scribe (3e génération)", "CURRENT", "noir et blanc, éclairage", "lecture Kindle + notes", "workflow de fichiers moins ouvert qu’Android"),
            ("Kindle Scribe Colorsoft", "CURRENT", "couleur, éclairage", "lecture et annotations couleur", "écosystème centré Amazon"),
            ("Kindle Scribe sans éclairage", "CURRENT", "16 Go, noir et blanc", "écriture/lecture avec configuration plus simple", "pas d’éclairage frontal"),
            ("Kindle Scribe 2024", "PREVIOUS_GENERATION", "noir et blanc", "ancienne génération encore supportée", "pas toutes les nouvelles connexions cloud"),
        ],
        "ecosystem": [
            ("Bibliothèque", "Kindle Store et bibliothèque Kindle."),
            ("Stylet", "Premium Pen sur les nouvelles générations documentées."),
            ("Workspace", "réunit livres, documents et carnets sur les modèles 2025+."),
            ("Notes", "carnets, écriture manuscrite, recherche sur nouvelles générations."),
            ("Documents", "Send to Kindle et import de formats compatibles."),
            ("Cloud tiers", "Google Drive et OneDrive pour modèles 2025+, avec import/export de copies plutôt que synchronisation bidirectionnelle."),
            ("OneNote", "export de carnets en texte ou image selon le flux proposé."),
            ("Partage", "email et PDF, avec conversion/recherche selon les fonctions."),
        ],
        "strengths": ["lecture Kindle très intégrée", "nouvelles générations nettement plus ouvertes au cloud de travail", "un même appareil pour livres, documents et carnets"],
        "limits": ["les fichiers importés depuis Drive/OneDrive ne se synchronisent pas automatiquement en retour", "les fonctions cloud modernes exigent un Scribe sorti en 2025 ou après", "moins orienté organisation complexe de connaissances que Supernote ou BOOX"],
        "choose": ["la lecture Kindle reste une part importante de votre usage", "vous voulez annoter des documents sans quitter l’écosystème Amazon", "vous appréciez les nouvelles connexions Drive/OneDrive sans avoir besoin d’Android complet"],
        "avoid": ["vous voulez une vraie synchronisation bidirectionnelle des fichiers cloud", "vous avez besoin d’applications tierces nombreuses", "vous recherchez un système de liens et de structuration de notes très avancé"],
    },
    "kobo": {
        "name": "Kobo Elipsa",
        "positioning": "une liseuse grand format centrée sur l’écosystème Kobo, qui ajoute stylet, carnets, annotation PDF et transferts Google Drive/Dropbox sans devenir une tablette Android généraliste",
        "current_range": [("Kobo Elipsa 2E", "CURRENT", "10,3″ Carta 1200, 32 Go", "lecture, PDF et carnets", "annotations EPUB manuscrites peu portables"), ("Kobo Elipsa", "PREVIOUS_GENERATION", "10,3″", "ancienne génération", "moins pertinente face à l’Elipsa 2E actuelle")],
        "ecosystem": [("Bibliothèque", "Kobo Store et livres Kobo."), ("Stylet", "Kobo Stylus / Stylus 2 selon compatibilité."), ("Carnets", "Basic et Advanced notebooks, recherche et conversion manuscrite."), ("PDF", "annotation possible sur PDF non protégés."), ("EPUB", "annotation manuscrite possible, mais export limité selon le type de contenu."), ("Cloud", "Kobo Cloud pour carnets, plus Google Drive et Dropbox."), ("Import", "PDF et EPUB non protégés via Google Drive sur modèles compatibles."), ("Partage", "export de carnets et PDF annotés selon format et droits.")],
        "strengths": ["lecture et prise de notes réunies dans un environnement simple", "Google Drive et Dropbox intégrés sur l’Elipsa 2E", "éclairage ComfortLight PRO et grand écran pour lecture documentaire"],
        "limits": ["les annotations manuscrites EPUB restent liées à la liseuse et ne s’exportent pas comme un PDF annoté", "les PDF protégés par DRM ne se prêtent pas à l’annotation manuscrite", "moins d’outils de gestion de connaissances qu’un Supernote ou BOOX"],
        "choose": ["vous lisez beaucoup dans l’écosystème Kobo", "vous voulez annoter des PDF et créer des carnets sans tablette Android", "Google Drive ou Dropbox suffit pour votre circulation de documents"],
        "avoid": ["vous devez exporter toutes vos annotations de livres vers d’autres outils", "vous avez besoin d’applications métier", "votre priorité est une organisation sophistiquée de centaines de notes liées"],
    },
    "supernote": {
        "name": "Supernote",
        "positioning": "des e-notebooks spécialisés dans l’écriture et l’organisation de connaissances, avec liens, titres, reconnaissance manuscrite, transferts cloud et une forte logique de réparabilité",
        "current_range": [("Supernote Manta", "CURRENT", "10,7″, 300 ppp, sans éclairage", "écriture, PDF, notes structurées", "pas de couleur ni de lumière frontale"), ("Supernote Nomad", "CURRENT", "format compact", "mobilité et notes personnelles", "surface réduite pour grands PDF"), ("A5 X / A6 X", "PREVIOUS_GENERATION", "ancienne nomenclature", "parc installé", "à distinguer de Manta/Nomad")],
        "ecosystem": [("Matériel", "Manta et Nomad, conception modulaire avec batterie/stockage selon modèle."), ("Stylet", "écosystème de stylos avec pointe céramique NeverReplace."), ("Système", "Chauvet, système Android 11 spécialisé."), ("Notes", "liens, headings, mots-clés, étoiles et organisation orientée connaissances."), ("OCR", "reconnaissance manuscrite en temps réel, export TXT/DOCX."), ("Cloud", "Supernote Cloud, Dropbox et Google Drive documentés."), ("Transfert", "USB-C, email, réseau local et Browse & Access."), ("Applications", "apps compagnon desktop/mobile et intégration Kindle.")],
        "strengths": ["organisation des notes particulièrement poussée", "reconnaissance manuscrite et export texte sans abonnement récurrent annoncé", "conception modulaire et réparabilité mises en avant sur Manta/Nomad"],
        "limits": ["pas d’éclairage frontal sur Manta", "pas d’écran couleur dans la gamme actuelle documentée", "moins d’applications généralistes qu’une BOOX Android ouverte"],
        "choose": ["vous construisez un système de notes reliées plutôt qu’un simple carnet", "vous voulez garder un workflow sans abonnement pour la reconnaissance manuscrite", "vous valorisez la réparabilité et le stockage extensible"],
        "avoid": ["vous avez besoin de couleur ou de lumière frontale", "vous utilisez beaucoup d’applications tierces Android", "la lecture commerciale Kindle/Kobo est votre besoin dominant"],
    },
}
