"""Curated visual routing for guide pages.

The goal is deliberately NOT to give every guide an image. A guide keeps a
functional diagram only when the visual adds a representation that the HTML
content does not already provide. Other guides are explicitly routed to
no_visual until a useful editorial image is produced.
"""

VISUALS = {
    "annoter-pdf-tablette-e-ink": {
        "asset_mode": "functional_diagram",
        "type": "process_flow",
        "visual_goal": "Montrer le parcours complet d'un PDF, de l'import à la vérification du fichier exporté.",
        "title": "Annoter un PDF sans casser le workflow",
        "subtitle": "Le bon appareil doit gérer tout le parcours, pas seulement l'écriture.",
        "alt": "Schéma du parcours d'un PDF : import, annotation, export et vérification du fichier final.",
        "caption": "Testez un PDF réel de bout en bout avant de choisir un appareil.",
        "steps": [["Importer", "Ouvrir le PDF dans l'appareil"], ["Annoter", "Écrire, surligner, naviguer"], ["Exporter", "Créer une copie exploitable"], ["Vérifier", "Ouvrir le fichier sur ordinateur"]],
    },
    "autonomie-tablette-e-ink": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter une checklist graphique qui répète les facteurs déjà expliqués dans le guide.",
        "reason": "Les facteurs d'autonomie sont mieux servis par le texte et les listes HTML ; la checklist SVG était une duplication visuelle sans valeur supplémentaire.",
    },
    "bloc-notes-numerique-avec-ou-sans-abonnement": {
        "asset_mode": "functional_diagram",
        "type": "decision_tree",
        "visual_goal": "Faire bifurquer la décision selon qu'une fonction essentielle dépend ou non d'un abonnement.",
        "title": "L'abonnement est-il un vrai critère d'achat ?",
        "subtitle": "Séparez fonctions essentielles, confort cloud et services optionnels.",
        "alt": "Arbre de décision pour savoir si un abonnement doit peser dans le choix d'un bloc-notes numérique.",
        "caption": "Un abonnement ne doit compter que s'il touche une fonction dont vous avez réellement besoin.",
        "nodes": [
            {"id": "start", "x": 390, "y": 130, "w": 420, "h": 82, "style": "primary", "lines": ["Une fonction essentielle", "dépend-elle d'un abonnement ?"]},
            {"id": "yes", "x": 150, "y": 330, "w": 330, "h": 100, "style": "muted", "lines": ["Oui", "Calculez le coût récurrent"]},
            {"id": "no", "x": 720, "y": 330, "w": 330, "h": 100, "style": "muted", "lines": ["Non", "Comparez d'abord l'usage"]},
            {"id": "yes2", "x": 130, "y": 560, "w": 370, "h": 120, "style": "accent", "lines": ["Vérifiez la dépendance", "cloud, stockage, export", "ou fonctions avancées"]},
            {"id": "no2", "x": 700, "y": 560, "w": 370, "h": 120, "style": "accent", "lines": ["Traitez l'abonnement", "comme un confort", "et non un coût obligatoire"]},
        ],
        "edges": [{"from": "start", "to": "yes", "label": "Oui"}, {"from": "start", "to": "no", "label": "Non"}, {"from": "yes", "to": "yes2"}, {"from": "no", "to": "no2"}],
    },
    "bloc-notes-numerique-couleur-ou-noir-et-blanc": {
        "asset_mode": "functional_diagram",
        "type": "decision_tree",
        "visual_goal": "Montrer quand la couleur transporte réellement une information utile.",
        "title": "La couleur change-t-elle réellement votre travail ?",
        "subtitle": "Le bon critère est l'information portée par la couleur.",
        "alt": "Arbre de décision pour choisir entre un écran E Ink couleur et noir et blanc.",
        "caption": "Choisissez la couleur lorsqu'elle transporte une information utile dans vos documents ou annotations.",
        "nodes": [
            {"id": "start", "x": 390, "y": 120, "w": 420, "h": 82, "style": "primary", "lines": ["La couleur porte-t-elle", "une information utile ?"]},
            {"id": "yes", "x": 130, "y": 320, "w": 380, "h": 110, "style": "muted", "lines": ["Oui", "schémas, corrections,", "légendes ou repères"]},
            {"id": "no", "x": 690, "y": 320, "w": 380, "h": 110, "style": "muted", "lines": ["Non", "texte, notes et PDF", "principalement monochromes"]},
            {"id": "colour", "x": 130, "y": 560, "w": 380, "h": 120, "style": "accent", "lines": ["Examinez les modèles", "E Ink couleur", "et leurs compromis"]},
            {"id": "bw", "x": 690, "y": 560, "w": 380, "h": 120, "style": "accent", "lines": ["Le noir et blanc", "peut rester le choix", "le plus simple"]},
        ],
        "edges": [{"from": "start", "to": "yes", "label": "Oui"}, {"from": "start", "to": "no", "label": "Non"}, {"from": "yes", "to": "colour"}, {"from": "no", "to": "bw"}],
    },
    "bloc-notes-numerique-dropbox": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter un flux générique tablette-cloud-ordinateur qui n'explique rien de spécifique à Dropbox.",
        "reason": "Le process flow reprenait seulement les étapes déjà décrites et pouvait donner une fausse impression d'intégration universelle.",
    },
    "bloc-notes-numerique-google-drive": {
        "asset_mode": "no_visual",
        "visual_goal": "Ne pas transformer une intégration variable selon les marques en workflow générique trompeur.",
        "reason": "Le visuel import-annotation-export était trop générique et moins précis que le texte sur les différences d'implémentation.",
    },
    "bloc-notes-numerique-onedrive": {
        "asset_mode": "no_visual",
        "visual_goal": "Conserver la nuance sur les intégrations Microsoft plutôt qu'un schéma universel.",
        "reason": "Le process flow dupliquait le parcours narratif et ne représentait aucune propriété spatiale ou mécanique distincte.",
    },
    "convertir-notes-manuscrites-en-texte": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter de dupliquer le guide OCR avec un second diagramme presque identique.",
        "reason": "Le schéma écriture-reconnaissance-relecture-export est déjà couvert par le guide OCR ; garder les deux visuels crée une répétition inter-pages.",
    },
    "ecosysteme-ouvert-ou-ferme": {
        "asset_mode": "functional_diagram",
        "type": "decision_tree",
        "visual_goal": "Montrer l'ordre de décision entre besoins d'applications tierces et préférence pour un workflow spécialisé.",
        "title": "Ouvert ou fermé : partez de vos contraintes logicielles",
        "subtitle": "Le bon choix dépend surtout des applications et transferts indispensables.",
        "alt": "Arbre de décision pour choisir entre un écosystème spécialisé et un écosystème plus ouvert selon les applications et intégrations nécessaires.",
        "caption": "Le schéma montre le chemin de décision sans répéter le tableau détaillé.",
        "nodes": [
            {"id": "start", "x": 390, "y": 110, "w": 420, "h": 92, "style": "primary", "lines": ["Avez-vous besoin", "d'applications tierces précises ?"]},
            {"id": "apps_yes", "x": 90, "y": 300, "w": 400, "h": 105, "style": "muted", "lines": ["Oui", "vérifiez leur disponibilité", "et leurs droits d'accès"]},
            {"id": "apps_no", "x": 710, "y": 300, "w": 400, "h": 105, "style": "muted", "lines": ["Non", "un workflow spécialisé", "peut suffire"]},
            {"id": "integrations", "x": 70, "y": 530, "w": 440, "h": 125, "style": "accent", "lines": ["Priorité : ouverture", "apps, cloud, partage", "et intégrations tierces"]},
            {"id": "simplicity", "x": 690, "y": 530, "w": 440, "h": 125, "style": "accent", "lines": ["Priorité : simplicité", "workflow cohérent", "et moins de réglages"]},
        ],
        "edges": [{"from": "start", "to": "apps_yes", "label": "Oui"}, {"from": "start", "to": "apps_no", "label": "Non"}, {"from": "apps_yes", "to": "integrations"}, {"from": "apps_no", "to": "simplicity"}],
    },
    "encre-electronique-fonctionnement": {
        "asset_mode": "functional_diagram",
        "type": "process_flow",
        "visual_goal": "Relier le mécanisme électrophorétique à la persistance de l'image.",
        "title": "Pourquoi une image E Ink reste affichée",
        "subtitle": "Le principe électrophorétique explique la faible consommation et le rafraîchissement.",
        "alt": "Schéma simplifié du fonctionnement de l'encre électronique, de la commande électrique à l'image visible.",
        "caption": "Le schéma simplifie le mécanisme pour relier fonctionnement technique et conséquence d'usage.",
        "steps": [["Commande", "Une tension est appliquée"], ["Particules", "Les pigments se déplacent"], ["Pixel", "La surface change d'apparence"], ["Image", "Elle reste visible sans rafraîchissement continu"]],
    },
    "exporter-notes": {
        "asset_mode": "no_visual",
        "visual_goal": "Ne pas illustrer une simple succession note-format-canal-destination déjà évidente dans le contenu.",
        "reason": "Le process flow reformulait littéralement le texte sans mécanisme ni bifurcation utile.",
    },
    "formats-fichiers-compatibles": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter une checklist graphique redondante avec les vérifications HTML du guide.",
        "reason": "La checklist SVG était une seconde version d'une liste éditoriale ; le HTML est plus accessible, plus précis et maintenable.",
    },
    "imprimer-notes-numeriques": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter un flux export-contrôle-impression trop trivial pour justifier une image.",
        "reason": "Le schéma n'apportait aucune compréhension supplémentaire par rapport aux étapes du guide.",
    },
    "latence-ecriture": {
        "asset_mode": "functional_diagram",
        "type": "process_flow",
        "visual_goal": "Montrer que la latence perçue est une chaîne de traitement et pas une seule spécification.",
        "title": "D'où vient la latence d'écriture ?",
        "subtitle": "Le délai perçu est une chaîne, pas une seule spécification.",
        "alt": "Schéma des étapes qui contribuent à la latence entre le mouvement du stylet et l'affichage du trait.",
        "caption": "La sensation finale dépend du stylet, du système, du rendu et du rafraîchissement de l'écran.",
        "steps": [["Stylet", "Mouvement détecté"], ["Numériseur", "Position transmise"], ["Logiciel", "Trait calculé"], ["Écran E Ink", "Trait rendu et rafraîchi"]],
    },
    "liseuse-ou-bloc-notes-numerique": {
        "asset_mode": "functional_diagram",
        "type": "decision_tree",
        "visual_goal": "Faire choisir une catégorie à partir de l'activité dominante plutôt que recopier le tableau comparatif.",
        "title": "Liseuse, hybride ou bloc-notes : partez de l'activité dominante",
        "subtitle": "Le tableau détaille les fonctions ; ce schéma montre la bifurcation de choix.",
        "alt": "Arbre de décision entre liseuse, appareil hybride avec stylet et bloc-notes numérique selon la place de la lecture, de l'écriture et de l'export.",
        "caption": "Utilisez le tableau pour les détails et ce schéma uniquement pour le chemin de décision.",
        "nodes": [
            {"id": "start", "x": 390, "y": 100, "w": 420, "h": 90, "style": "primary", "lines": ["Votre activité dominante", "est-elle la lecture ?"]},
            {"id": "read_yes", "x": 80, "y": 280, "w": 400, "h": 105, "style": "muted", "lines": ["Oui", "les notes servent-elles", "surtout à commenter ?"]},
            {"id": "read_no", "x": 720, "y": 280, "w": 400, "h": 105, "style": "muted", "lines": ["Non", "écriture, PDF et export", "structurent le travail"]},
            {"id": "reader", "x": 40, "y": 520, "w": 300, "h": 120, "style": "accent", "lines": ["Liseuse", "lecture d'abord", "annotations secondaires"]},
            {"id": "hybrid", "x": 450, "y": 520, "w": 300, "h": 120, "style": "accent", "lines": ["Hybride", "lecture + stylet", "réellement équilibrés"]},
            {"id": "notebook", "x": 860, "y": 520, "w": 300, "h": 120, "style": "accent", "lines": ["Bloc-notes", "écriture, organisation", "et export d'abord"]},
        ],
        "edges": [{"from": "start", "to": "read_yes", "label": "Oui"}, {"from": "start", "to": "read_no", "label": "Non"}, {"from": "read_yes", "to": "reader", "label": "Oui"}, {"from": "read_yes", "to": "hybrid", "label": "Non"}, {"from": "read_no", "to": "notebook"}],
    },
    "ocr-manuscrit": {
        "asset_mode": "functional_diagram",
        "type": "process_flow",
        "visual_goal": "Montrer que la reconnaissance manuscrite produit un texte à relire avant réutilisation.",
        "title": "Ce que fait réellement l'OCR manuscrit",
        "subtitle": "Reconnaître, relire, puis réutiliser.",
        "alt": "Schéma du traitement OCR d'une note manuscrite jusqu'au texte réutilisable.",
        "caption": "La reconnaissance produit un brouillon à vérifier, pas une transcription infaillible.",
        "steps": [["Manuscrit", "Écriture capturée"], ["Reconnaissance", "Analyse des caractères"], ["Correction", "Vérifier noms et erreurs"], ["Réutilisation", "Copier, exporter ou rechercher"]],
    },
    "organiser-notes-numeriques": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter un diagramme capturer-nommer-classer-retrouver qui reprend directement les conseils du guide.",
        "reason": "Le process flow était une paraphrase graphique et ne justifiait pas un asset supplémentaire.",
    },
    "prix-bloc-notes-numerique": {
        "asset_mode": "no_visual",
        "visual_goal": "Ne pas redessiner sous forme graphique la composition du coût déjà traitée en tableaux et texte.",
        "reason": "Le cost breakdown était une forme de tableau déguisé et répétait la logique de coût total déjà expliquée dans la page de référence.",
    },
    "synchroniser-notes-cloud": {
        "asset_mode": "functional_diagram",
        "type": "ecosystem_map",
        "visual_goal": "Montrer les relations entre appareil, service cloud, autres appareils et export indépendant.",
        "title": "Synchroniser n'est pas simplement copier un fichier",
        "subtitle": "Suivez ce qui se passe entre l'appareil, le cloud et les autres appareils.",
        "alt": "Carte d'écosystème montrant la tablette, le service cloud, les autres appareils et l'export.",
        "caption": "Vérifiez la direction des échanges, les conflits et ce qui reste accessible hors ligne.",
        "layers": [["Tablette", "Notes et documents"], ["Service cloud", "Synchronisation ou stockage"], ["Autres appareils", "Mobile et ordinateur"], ["Export", "Copie indépendante pour archive ou partage"]],
    },
    "tablette-classique-ou-tablette-e-ink": {
        "asset_mode": "functional_diagram",
        "type": "decision_tree",
        "visual_goal": "Faire partir le choix des contraintes éliminatoires plutôt que reproduire le tableau comparatif.",
        "title": "Tablette classique ou E Ink : identifiez votre contrainte éliminatoire",
        "subtitle": "Commencez par ce qui doit absolument fonctionner.",
        "alt": "Arbre de décision entre tablette classique et tablette E Ink selon les applications, la vidéo et le temps passé à lire ou écrire.",
        "caption": "Le schéma montre l'ordre de décision ; le tableau HTML conserve la comparaison détaillée.",
        "nodes": [
            {"id": "start", "x": 390, "y": 100, "w": 420, "h": 90, "style": "primary", "lines": ["Avez-vous besoin", "d'apps, vidéo ou animation ?"]},
            {"id": "classic", "x": 90, "y": 310, "w": 400, "h": 115, "style": "accent", "lines": ["Oui", "tablette classique", "à examiner en priorité"]},
            {"id": "focus", "x": 710, "y": 310, "w": 400, "h": 115, "style": "muted", "lines": ["Non", "passez-vous surtout", "du temps à lire et écrire ?"]},
            {"id": "eink", "x": 690, "y": 540, "w": 440, "h": 125, "style": "accent", "lines": ["Oui", "E Ink devient cohérent", "si le workflow suit"]},
            {"id": "classic2", "x": 70, "y": 540, "w": 440, "h": 125, "style": "muted", "lines": ["Non", "la polyvalence d'une", "tablette classique reste utile"]},
        ],
        "edges": [{"from": "start", "to": "classic", "label": "Oui"}, {"from": "start", "to": "focus", "label": "Non"}, {"from": "focus", "to": "eink", "label": "Oui"}, {"from": "focus", "to": "classic2", "label": "Non"}],
    },
    "tablette-e-ink": {
        "asset_mode": "functional_diagram",
        "type": "ecosystem_map",
        "visual_goal": "Relier matériel, couche d'affichage, logiciel et sortie des documents dans un seul modèle mental.",
        "title": "Une tablette E Ink est un système, pas seulement un écran",
        "subtitle": "Le confort final dépend de la chaîne complète entre saisie, logiciel et sortie.",
        "alt": "Carte simplifiée d'une tablette E Ink reliant stylet, écran, système de notes, cloud et export.",
        "caption": "Évaluez la chaîne complète : entrée, traitement, affichage et sortie des documents.",
        "layers": [["Entrée", "Stylet, tactile, fichiers"], ["Système", "OS, notes, lecteur PDF"], ["Écran E Ink", "Affichage et rafraîchissement"], ["Sortie", "Cloud, export, ordinateur"]],
    },
    "taille-ecran-bloc-notes-numerique": {
        "asset_mode": "functional_diagram",
        "type": "size_comparison",
        "visual_goal": "Représenter physiquement la différence de surface entre familles de tailles d'écran.",
        "title": "La taille d'écran change la surface de travail et la mobilité",
        "subtitle": "Comparez le format au document que vous manipulez le plus souvent.",
        "alt": "Comparaison visuelle de plusieurs tailles d'écran courantes pour les bloc-notes numériques.",
        "caption": "Les tailles sont illustratives : vérifiez toujours les dimensions physiques du modèle précis.",
        "sizes": [["7,8″", 78, 104, "Très mobile"], ["10,3″", 103, 137, "Compromis courant"], ["11,8″", 118, 157, "Plus de surface"], ["13,3″", 133, 177, "Grands PDF"]],
    },
    "transfert-notes-vers-ordinateur": {
        "asset_mode": "no_visual",
        "visual_goal": "Éviter un schéma de transfert générique alors que USB, cloud et applications diffèrent selon les appareils.",
        "reason": "Le diagramme simplifiait excessivement les méthodes de transfert et répétait les options déjà expliquées dans le guide.",
    },
}
